# Generated by Django 5.2 on 2025-05-07 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_d', models.ImageField(blank=True, null=True, upload_to='docente')),
                ('especialidad', models.CharField(max_length=100)),
                ('titulo', models.CharField(choices=[('Lic.', 'Licenciatura'), ('Ing.', 'Ingeniería'), ('Mtra.', 'Maestría'), ('Dr.', 'Doctorado')], max_length=10)),
                ('usuario_d', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
